config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'entities#index'
  resources :entities do
    post :add_child, on: :member
  end

end

app/models/entity.rb
# frozen_string_literal: true
module Entity
  KINDS = %w(Ability Axiom Context Domain Inference Layer Model Example Stock Story).freeze
  ABSTRACT = Struct.new 'Abstract', :id, :name, :kind, :layer_id
end

app/models/entity/depend.rb
# frozen_string_literal: true
module Entity
  class Depend
    # Inference or layer dependency
    # it is a leaf entity

    # in tree: persist as deps in hash like
    # { inference: { depends: [23, 42] }} where first key inference
    # in code: dependency line
    # in spec: maybe let ?
    # in filesystem: nothing

    attr_reader :id, :layer_id, :name, :code, :addictance
    def initialize(entity, addictance = 1)
      @id = entity.id
      @layer_id = entity.layer_id
      @name = "id: #{id} #{entity.kind}::#{entity.layer&.name}.#{entity.name}"
      @code = "  # #{entity.parent.name}.#{entity.name}"
      @addictance = addictance
    end

    def addicted?
      addictance != 0
    end

    # used from dependency_form
    def persisted?
      true
    end
  end
end

app/models/entity/picker.rb
# frozen_string_literal: true
module Entity
  class Picker < Struct.new 'Picker', :repo, :producer
    def possibly_kinds
      return ['Domain'] if repo.parent_id.nil?
      Entity::KINDS & repo.parent.producer.child_kinds
    end

    def possibly_child_kinds
      Entity::KINDS & producer.child_kinds
    end

    def possibly_abstract_list
      repo.root.descendants.where(kind: producer.abstract_kind)
    end

    def kinds_list
      possibly_kinds.map.with_index { |obj, index| [index, obj] }
    end

    def child_kinds_list
      possibly_child_kinds.map.with_index { |obj, index| [index, obj] }
    end
  end
end

app/models/entity/presenter.rb
# frozen_string_literal: true
module Entity
  class Presenter < Struct.new 'Presenter', :repo, :producer
    def stories
      repo.root.descendants.stories
    end

    def sentence
      producer.sentence
    end

    def description
      repo.desc
    end

    def inheritance_tree
      indent(producer.to_tree)
    end

    def path_line
      '# ' + producer.to_ruby_path
    end

    def produced_code
      indent(producer.to_ruby)
    end

    def produced_spec
      indent(producer.to_spec)
    end

    def abstractable?
      producer.abstractable?
    end

    def sentences?
      !repo.root?
    end

    def hash_tree
      repo.root.hash_tree
    end

    private

    def indent(unindented_array, depth = 0)
      indented_array = []
      unindented_array.each do |element|
        indented_array << if element.class == Array
                            indent(element, (depth + 2))
                          else
                            indent_line(element.to_s, depth)
        end
      end
      indented_array.flatten.join("\n")
    end

    def indent_line(line, depth = 0)
      ' ' * depth + line
    end
  end
end

app/models/entity/producer.rb
# frozen_string_literal: true
module Entity
  class Producer < Struct.new 'Producer', :repo
    def self.wrap(repo)
      new(repo).build_concrete_producer
    end

    def build_concrete_producer
      full_kind.constantize.new repo
    end

    private

    def full_kind
      'Produce::' + safe_kind
    end

    def safe_kind
      KINDS.include?(repo.kind) ? repo.kind : 'Aught'
    end
  end
end

app/models/entity/repo.rb
# frozen_string_literal: true
module Entity
  class Repo < Layers::Repo
    self.table_name = 'entities'
    acts_as_tree dependent: :destroy, order: 'sort_order'

    belongs_to :abstract, class_name: 'Repo'
    has_many :exemplars, class_name: 'Repo', foreign_key: 'abstract_id', dependent: :destroy

    scope :abilities, -> { where(kind: 'Ability') }
    scope :axioms, -> { where(kind: 'Axiom') }
    scope :contexts, -> { where(kind: 'Context') }
    scope :inferences, -> { where(kind: 'Inference') }
    scope :layers, -> { where(kind: 'Layer') }
    scope :models, -> { where(kind: 'Model') }
    scope :examples, -> { where(kind: 'Example') }
    scope :stocks, -> { where(kind: 'Stock') }
    scope :stories, -> { where(kind: 'Story') }

    after_commit :try_update_context_tree, on: [:create, :update]

    def presenter
      Presenter.new self, producer
    end

    def producer
      Producer.wrap(self)
    end

    def title
      abstract.nil? ? name : abstract.name
    end

    def possibly_kinds
      return ['Domain'] if parent_id.nil?
      Entity::KINDS & parent.producer.child_kinds
    end

    def possibly_child_kinds
      Entity::KINDS & producer.child_kinds
    end

    def possibly_abstract_list
      parent.siblings.where(kind: producer.abstract_kind)
    end

    def kinds_list
      possibly_kinds.map.with_index { |obj, index| [index, obj] }
    end

    def child_kinds_list
      possibly_child_kinds.map.with_index { |obj, index| [index, obj] }
    end

    ## Possible values to collection select & validation
    def parents_list
      root.self_and_descendants
    end

    def add_child(params)
      child = children.build(params)
      child.kind_num = params[:kind_num]
      child.save
      child.try_update_context_tree
      child
    end

    ## kind num getter
    def kind_num
      possibly_kinds.rindex kind
    end

    ## kind setter by num
    def kind_num=(num)
      self.kind = kind_by_num(num)
    end

    def kind_by_num(num)
      possibly_kinds[num.to_i] || 'Story'
    end

    def try_update_context_tree
      case kind
      when 'Axiom'
        ancestors.abilities.first&.producer&.update_context_tree!
      when 'Inference'
        producer.axioms.each do |axiom|
          axiom.parent.producer.update_context_tree!
        end
      when 'Example'
        ancestors.abilities.first.producer.update_context_tree!
      end
    end
  end
end

app/controllers/entities_controller.rb
# frozen_string_literal: true
class EntitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entity, only: [:add_child, :show, :edit, :update, :destroy]

  # GET /entities
  # GET /entities.json
  def index
    @entities = Entity::Repo.roots
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
    @presenter = @entity.presenter
  end

  # GET /entities/new
  def new
    @entity = Entity::Repo.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities
  # POST /entities.json
  def create
    @entity = Entity::Repo.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_child
    @entity.add_child(entity_params.merge(parent: @entity))
    redirect_to entity_path @entity
  end

  # PATCH/PUT /entities/1
  # PATCH/PUT /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity.destroy
    respond_to do |format|
      format.html do
        redirect_to entity_path @entity.root? ? entities_url : @entity.parent,
                                notice: 'Entity was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity::Repo.find(params[:id])
  end

  # FIXME: need to set manually param obj name instead entity_repo
  def entity_params
    params.require(:entity_repo).permit(
      :parent_id,
      :abstract_id,
      :sort_order,
      :kind_num,
      :name,
      :desc
    )
  end
end

app/helpers/entities_helper.rb
# frozen_string_literal: true
module EntitiesHelper
end

app/views/entities/_dependency_form.html.slim
h3 class='text-muted' "Add dependencies from #{layer.name}"

= bootstrap_form_for entity, url: entity_path(entity) do |form|
  = form.fields_for :possibly_deps do |depend|
    = depend.hidden_field :id, value: depend.object.id 
    = depend.check_box :addict, label: depend.object.name
  
  = form.submit 'Save Dependencies'

app/views/entities/_form.html.slim
= bootstrap_form_for @entity, url: entity_path(@entity) do |form|
  = form.collection_select :parent_id, @entity.parents_list, :id, :name, 
    include_blank: 'root'
  = form.collection_select :kind_num, @entity.kinds_list, :first, :last,
    label: 'Kind'
  = form.number_field :sort_order
  = form.text_field :name
  = form.text_area :desc
  = form.submit

app/views/entities/_layer_tabs.html.slim
ul class="nav nav-tabs" role="tablist"
  li.active role="presentation"
    a href="#abstract" aria-controls="profile" role="tab" data-toggle="tab"
      'Abstract
  - entity.layers_list.each do |layer|
    li role="presentation"
      a href="#layer_#{layer.id}" aria-controls="profile" role="tab" data-toggle="tab"
        = layer.name

div class="tab-content"
  div class="tab-pane active" role="tabpanel" id="abstract"
    p Abstract level of entity
    - unless entity.leaf?
      - entity.children.where(layer_id: nil).each do |child|
        h6
          = link_to child.name, entity_path(child), class: 'btn btn-link'
          ' | #{child.abstract.sentence}
  - entity.layers_list.each do |layer|
    div class="tab-pane" role="tabpanel" id="layer_#{layer.id}"
      p = layer.desc
      - entity.children.where(layer_id: layer.id).each do |child|
        h6
          = link_to child.name, entity_path(child), class: 'btn btn-link'
          ' | #{child.abstract.sentence}

app/views/entities/_preamble.html.slim
- unless entity.root?
  - entity.ancestors.reverse.each do |anc|
    p = anc.abstract.sentence
h3 = entity.abstract.sentence
p = entity.desc

app/views/entities/_tabs.html.slim
ul class="nav nav-tabs" role="tablist"
  li.active role="presentation"
    a href="#abstract" aria-controls="profile" role="tab" data-toggle="tab"
      'Abstract
  - entity.layers_list.each do |layer|
    li role="presentation"
      a href="#layer_#{layer.id}" aria-controls="profile" role="tab" data-toggle="tab"
        = layer.name

div class="tab-content"
  div class="tab-pane active" role="tabpanel" id="abstract"
    p Abstract level of entity
    - unless entity.leaf?
      - entity.children.where(layer_id: nil).each do |child|
        h6
          = link_to child.name, entity_path(child), class: 'btn btn-link'
          ' | #{child.abstract.sentence}
  - entity.layers_list.each do |layer|
    div class="tab-pane" role="tabpanel" id="layer_#{layer.id}"
      p = layer.desc
      - entity.children.where(layer_id: layer.id).each do |child|
        h6
          = link_to child.name, entity_path(child), class: 'btn btn-link'
          ' | #{child.abstract.sentence}

app/views/entities/_trees.html.erb
<div id="tree" class="treeview"></div>

<script type="text/javascript">
  $(function() {
    var tree = [<%= raw render(
      partial: 'entities/tree', formats: :json,
      locals: {
        entity: entity,
        entity_id: entity_id
      }) %>];
    $('#tree').treeview({
      data: tree,
      showTags: true,
      enableLinks: true
    });
  });
</script>

app/views/entities/edit.html.slim
h1 Editing entity

= render 'entities/forms/main', entity: @entity

= link_to 'Back', entity_path(@entity), id: 'action-back'

app/views/entities/index.html.slim
h1 Entities

table class="table table-hover"
  tbody
    - @entities.each do |entity|
      tr.h4
        td = entity.parent_id
        td = entity.producer.sentence
        td = link_to 'Show', entity_path(entity)
        td = link_to 'Edit', edit_entity_path(entity)
        td = link_to 'Destroy', entity_path(entity), data: {:confirm => 'Are you sure?'}, :method => :delete

br

.btn.btn-success
  = link_to 'New Entity', new_entity_path

app/views/entities/new.html.slim
h1 New entity

= bootstrap_form_for @entity, url: entities_path do |form|
  = form.collection_select :kind_num, @entity.kinds_list, :first, :last,
    label: 'Kind'
  = form.text_field :name
  = form.text_area :desc
  = form.submit

= link_to 'Back', entities_path

app/views/entities/show.html.slim
.row
  .col-md-5
    h2 class='text-muted' Confusion
    = render 'entities/parts/tree_nav',
    entity: @entity.root,
    entity_id: @entity.id,
    hash_tree: @presenter.hash_tree
    = render 'entities/parts/map', presenter: @presenter

  .col-md-6.col-md-offset-1
    h2 class='text-muted' Discord
    / = render 'entities/parts/preamble', presenter: @presenter
    = render 'entities/parts/details', entity: @entity
    = render 'entities/forms/child', entity: @entity
    = render 'entities/parts/stories', presenter: @presenter
    - if @presenter.abstractable?
      = render 'entities/forms/abstract', entity: @entity

    = render 'entities/parts/code', presenter: @presenter